version: '3.8'

services:

  app:
    build: .
    container_name: kursovoy-app
    ports:
      - "8080:8080"
    platform: linux/arm64
    depends_on:
      - postgres
      - kafka
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/carrental
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: minio-test-bucket

  postgres:
    image: postgres:17
    container_name: kursovoy-postgres
    environment:
      POSTGRES_DB: carrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_reviews:
    image: postgres:17
    container_name: kursovoy-postgres-reviews
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: carrental_reviews
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_reviews:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: my-cluster-id
    volumes:
      - kafka_data:/bitnami/kafka

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "45733:45733"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":45733"

  reviewservice:
    build:
      context: /Users/aleksandremelanenko/Documents/Универ/ReviewService
    container_name: reviewservice
    depends_on:
      - postgres_reviews
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_reviews:5432/carrental_reviews
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"

volumes:
  postgres_data:
  postgres_data_reviews:
  kafka_data:
  minio_data: